version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - echo checking python version
      - python --version
      - echo making our scripts executable
  build:
    commands:
      - echo "nigga hit'em up"
