version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - echo checking python version
      - python --version
      - echo "building the container"
      - bash build_docker_image.sh
  build:
    commands:
      - echo "launching the container"
      - docker run -p 8080:5201 -d $DOCKER_USERNAME/$IMAGE_TAG
  post_build:
    commands:
      - echo "creating an image to our docker hub repo"
      - bash push_image.sh
